name: ğŸš€ Release + Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release (e.g. 1.2.3)
        required: false
        default: conventional
        type: string

      run-tests:
        description: Run tests before release
        required: false
        default: false
        type: boolean

jobs:
  test:
    if: github.event.inputs.run-tests == 'true'
    permissions: {}
    uses: ./.github/workflows/tests.yml
    with:
      run-on-windows: true

  release:
    name: ğŸš€ Release
    needs: test
    if: ${{ !cancelled() && (needs.test.result == 'success' || needs.test.result == 'skipped') }}
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      attestations: write

    steps:
      - name: ğŸ” Authentication for pushing to the main branch
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: ğŸ“¥ Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          # Required for fetching tags and generating release notes
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: true

      - name: ğŸ”§ Setup Bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2

      - name: ğŸ“¦ Install dependencies
        run: bun ci

      - name: ğŸ¤– Setup GitHub Actions Bot
        uses: cli-stuff/setup-github-actions-bot@6f48e564efbb89283f4ec530312d3cfd23a95f58 # v0.1

      - name: ğŸ“ˆ Bump version
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: bunx bumpp@^10.2.0 $VERSION --commit --tag --push --yes --no-verify

      - name: ğŸ› ï¸ Build package
        run: bun run build

      - name: ğŸ“œ Generate changelog and create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bunx npx https://pkg.pr.new/gitpaper@e7cac21 --release

      - name: ğŸ“¦ Publish to NPM Registry
        run: bunx npm publish
